name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Version ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v6.0.0
          - v5.1.1
          - v4.11.1
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - uses: docker/build-push-action@v4
      with:
        build-args:
        - VERSION=${{ matrix.version }}
